import type { Metadata } from "next";
// import { Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import HeaderMap from "@/components/map/HeaderMap";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <HeaderMap />

      <section>{children}</section>
    </main>
  );
}
